@TurnoPOS.Server_HostAddress = http://localhost:5248/api

POST {{TurnoPOS.Server_HostAddress}}/Department
Content-Type: application/json
{
  "name": "Bebidas"
}
###

POST {{TurnoPOS.Server_HostAddress}}/Department
Content-Type: application/json
{
  "name": "Comidas"
}
###

GET {{TurnoPOS.Server_HostAddress}}/Department
Accept: application/json

###


GET {{TurnoPOS.Server_HostAddress}}/Inventory?parentId=&isActive=false
Accept: application/json

###

GET {{TurnoPOS.Server_HostAddress}}/Inventory?parentId=0&isActive=true
Accept: application/json

###

GET {{TurnoPOS.Server_HostAddress}}/Inventory?parentId=1&isActive=true
Accept: application/json

###

GET {{TurnoPOS.Server_HostAddress}}/Inventory/6
Accept: application/json

###


GET {{TurnoPOS.Server_HostAddress}}/Order
Accept: application/json

###

GET {{TurnoPOS.Server_HostAddress}}/Order/1
Accept: application/json

###

GET {{TurnoPOS.Server_HostAddress}}/Order/10/print
Accept: application/json

###